version: '3'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=sangijidoukandb
  app:
    build: ./
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
